title: Sushil Murali # your name (or website title) here
logo: "/images/1671819847323.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sushil Murali is an experienced IT leader and business relationship manager with a MBA degree and a track record of delivering successful enterprise projects. He has expertise in PMO strategy, business analysis, agile and scrum methodologies, cross-functional collaboration, and onshore and offshore management. He has worked with various mid-sized and enterprise organizations to integrate technology and business operations and achieve strategic goals. He is proficient in MS Azure Devops, quality assurance, UAT, and executive-level KPI reporting. He recently led the end redesign and testing of a customer-centric, enterprise collaboration platform.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sushilkumarpm1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
