title: Sushil Murali # your name (or website title) here
logo: "/images/1671819847323.jpg" # your photo (or logo) here
description: (630)-390-4116 | Chicago, IL | Sushilkmar.pm@gmail.com
  <a href="https://www.linkedin.com/in/sushilkumarpm1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-VY9TG0VE10 # your Google Analytics tracking ID here
